spring:
  application:
    name: spring-boot-actuator

server:
  port: 8080

logging:
  pattern:
    level: ${spring.application.name:},%X{traceId:-},%X{spanId:-}

management:
#  server:
#    port: 8088
#    address: 127.0.0.1
  endpoints:
    jmx:
      exposure:
        include: health,info
    web:
      discovery:
        enabled: true
      base-path: /actuator
      path-mapping:
        health: health
      exposure:
        include: "*"
        exclude: threaddump
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST"
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true