version: '3.7'
services:
  standalone-mysql8:
    hostname: standalone-mysql8
    container_name: standalone-mysql8
    image: mysql:8.0.17
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=1000
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-u","root","-proot"]
      interval: 30s
      timeout: 1s
      retries: 20
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
      #volumes:
      - ./mysql/standalone/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    restart: always

