spring:
  elasticsearch:
    rest:
      uris: ${zlt.elasticsearch.uris}
      username: ${zlt.elasticsearch.username}
      password: ${zlt.elasticsearch.password}

zlt:
  indices:
    show: sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: com.central.search.controller