spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javastack
    username: root
    password: 12345678

mybatis-plus:
  type-aliases-package: cn.javastack.springboot.mybatisplus.entity