server:
  port: 8081

spring:
  boot:
    admin:
      client:
        url: http://localhost:8088
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

logging:
  file:
    name: ./logs/sba-client.log