jasypt:
  encryptor:
    password: G9w0BAQEFAASCBKYwggSiAgEAAoIBAQC
    property:
      prefix: "ENC@["
      suffix: "]"

javastack:
  username: ENC@[VA058GV86AaUx4wSoCKekKrDJv6tP4eTwWkoCGHnt6Tb3F7ETJnKAs3QiRkZFD5k]
  password: ENC@[7Y7FVXO5qS4lAx3o5B4atyHW8kGUv0o6903xL2ofTOicdcJw71/m+UeFUVfX0VPM]