# git clone https://github.com/prometheus-operator/kube-prometheus
# cd manifests

# kubectl  apply  -f setup/
# namespace/monitoring created
# customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com created
# customresourcedefinition.apiextensions.k8s.io/podmonitors.monitoring.coreos.com created
# customresourcedefinition.apiextensions.k8s.io/probes.monitoring.coreos.com created
# customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com created
# customresourcedefinition.apiextensions.k8s.io/prometheusrules.monitoring.coreos.com created
# customresourcedefinition.apiextensions.k8s.io/servicemonitors.monitoring.coreos.com created
# customresourcedefinition.apiextensions.k8s.io/thanosrulers.monitoring.coreos.com created
# clusterrole.rbac.authorization.k8s.io/prometheus-operator created
# clusterrolebinding.rbac.authorization.k8s.io/prometheus-operator created
# deployment.apps/prometheus-operator created
# service/prometheus-operator created
# serviceaccount/prometheus-operator created

# $ kubectl  apply -f  .
# alertmanager.monitoring.coreos.com/main created
# secret/alertmanager-main created
# service/alertmanager-main created
# serviceaccount/alertmanager-main created
# .............
# $ kubectl  get pods -n monitoring
# NAME                                   READY   STATUS    RESTARTS   AGE
# alertmanager-main-0                    1/2     Running   0          2d17h
# alertmanager-main-1                    1/2     Running   0          2d17h
# alertmanager-main-2                    1/2     Running   0          2d17h
# grafana-86445dccbb-m7kzg               1/1     Running   0          2d17h
# kube-state-metrics-5b67d79459-zf27k    3/3     Running   0          2d17h
# node-exporter-blx8m                    2/2     Running   0          2d17h
# node-exporter-zpns2                    2/2     Running   0          2d17h
# node-exporter-zrd6g                    2/2     Running   0          2d17h
# prometheus-adapter-66b855f564-mf9mc    1/1     Running   0          2d17h
# prometheus-k8s-0                       3/3     Running   1          2d17h
# prometheus-k8s-1                       3/3     Running   1          2d17h
# prometheus-operator-78fcb48ccf-sgklz   2/2     Running   0          2d17h

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-monitoring-service
  namespace: monitoring
spec:
  ingressClassName: nginx-default
  rules:
    - host: prometheus.taotaocloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-k8s
                port:
                  number: 9090
    - host: alertmanager.taotaocloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager-main
                port:
                  number: 9093
    - host: grafana.taotaocloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taotao-cloud-gateway-monitoring
  namespace: monitoring
  labels:
    app: taotao-cloud-gateway
spec:
  jobLabel: taotao-cloud-gateway-app
  #https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#servicemonitor
  endpoints:
    - port: taotao-cloud-gateway-port
      interval: 15s
      path: /actuator/prometheus
      scheme: http
  selector:
    matchLabels:
      app: taotao-cloud-gateway
  namespaceSelector:
    matchNames:
      - default
---
apiVersion: monitoring.coreos.com/v1 #这和ServiceMonitor一样
kind: PrometheusRule  #该资源类型是Prometheus，这也是一种自定义资源（CRD）
metadata:
  labels:
    app: "prometheus-rule-mysql"
    prometheus: kube-prometheus  #同ServiceMonitor，ruleSelector也会默认选择标签为prometheus: kube-prometheus的PrometheusRule资源
  name: prometheus-rule-mysql
spec:
  groups: #编写告警规则，和prometheus的告警规则语法相同
    - name: mysql.rules
      rules:
        - alert: TooManyErrorFromMysql
          expr: sum(irate(mysql_global_status_connection_errors_total[1m])) > 10
          labels:
            severity: critical
          annotations:
            description: mysql产生了太多的错误.
            summary: TooManyErrorFromMysql
        - alert: TooManySlowQueriesFromMysql
          expr: increase(mysql_global_status_slow_queries[1m]) > 10
          labels:
            severity: critical
          annotations:
            description: mysql一分钟内产生了{{ $value }}条慢查询日志.
            summary: TooManySlowQueriesFromMysql
