spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:myuser}
    password: ${RABBIT_MQ_PASSWORD:mypass}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info