########################全局配置##########################
global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.cn:465'          #设置邮件发送服务器地址
  smtp_from: 'test@qq.cn'                   #设置发件人
  smtp_auth_username: 'test@qq.cn'          #设置发件人
  smtp_auth_password: 'cbxxxxxxxxxxxxxx'    #设置发件人密码
  smtp_require_tls: false                   #是否启用TLS加密
#####################告警模板配置########################
templates:
  - 'template/*.tmpl'                       #设置告警模板位置
####################告警路由配置#########################
route:
  group_by: ['alertname']
  group_wait: 5m
  group_interval: 5m
  repeat_interval: 6h
  receiver: 'yunwei'                     #路由组名称
  routes:
##########设置自定义路由规则
#  - receiver: 'server-ERR'               #路由名称
#    group_wait: 30s                      #发送间隔
#    continue: true
#    match_re:
#      severity: "ERR"        #匹配prometheus的标签
####################告警发送配置########################
receivers:
  - name: 'yunwei'                                   #匹配路由组名称
    email_configs:
      - to: 'test@qq.cn'                                  #收件人
        html: '{{ template "mail.html" . }}'              #设置发送模板
        headers: { Subject: "[WARN] 服务异常-测试平台"}     #邮件标题
        send_resolved: true
      #webhook_configs:                                   #设置webhook地址
    # - url: 'http://172.0.0.1:31100/prometheusalert?type=fs&tpl=prometheus-fsv2&fsurl=https://open.feishu.cn/open-apis/bot/v2/hook/49b7cc23-4dff-4453-96a9-3bb80c5df704'
######################默认设置#############################
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
