name: Java CI
on: [push, pull_request]

jobs:
  buildOnJava17:
    name: build on java17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          cache: 'maven'
          java-version: 17
      - name: Build with Maven
        run: mvn package
