logging:
  level:
    ROOT: INFO

spring:
  # 在线诊断
  arthas:
    enabled: false
  # 内存数据库
#  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  # 关系数据库
  datasource:
    # 内存数据源
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: demo
    # 单数据源
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username:
#    password:
#    url: jdbc:mysql://localhost:3306/demo?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=${spring.application.name}
    # 多数据源，使用 @DS 切换
  #    dynamic:
  #      datasource:
  #        ds1:
  #          username:
  #          password:
  #          url: jdbc:mysql://localhost:3306/ds1?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  #          type: ${spring.datasource.type}
  #          driver-class-name: ${spring.datasource.driver-class-name}
  #        ds2:
  #          username:
  #          password:
  #          url: jdbc:mysql://localhost:3306/ds2?rewriteBatchedStatements=true&useSSL=false&useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  #          driver-class-name: ${spring.datasource.driver-class-name}
  #          type: ${spring.datasource.type}
  #      primary: ds1
  #      strict: true
  # 分库分表组件
  #  shardingsphere:
  #    props:
  #      sql.show: true
  #    datasource:
  #      names: demo
  #      demo:
  #        username: ${spring.datasource.dynamic.datasource.demo.username}
  #        password: ${spring.datasource.dynamic.datasource.demo.password}
  #        driver-class-name: ${spring.datasource.dynamic.datasource.demo.driver-class-name}
  #        jdbc-url: ${spring.datasource.dynamic.datasource.demo.url}
  #        type: ${spring.datasource.dynamic.datasource.demo.type}
  #    sharding:
  #      defaultDataSourceName: demo
  cloud:
    sentinel:
      enabled: true
      transport:
        dashboard: localhost:8090
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            groupId: sentinel
            dataId: ${spring.application.name}-flow-rule
            rule-type: flow
            data-type: json
  # 缓存数据库
  redis:
    enabled: false
    password:
    timeout: 5000
    database: 1
    host: localhost
    port: 6379
  # 模板引擎
  thymeleaf:
    cache: false
  # 链路跟踪
  zipkin:
    base-url: http://localhost:9411
  # 链路采集
  kafka:
    bootstrap-servers: localhost:9092

# 消息队列
rocketmq:
  enabled: false
  name-server: localhost:9876;localhost:9877
  producer:
    group: ${spring.application.name}
#    access-key:
#    secret-key:
  consumer:
    group: ${spring.application.name}
    topic: demo

# 分布式调度平台
#xxl:
#  job:
#    enable: false
#    access-token:
#    admin:
#      addresses: http://localhost:8090/xxljob
#    executor:
#      app-name: ${spring.application.name}
#      ip:
#      port: 8080
#      log-path: /data/applogs/xxl-job/jobhandler/
#      log-retention-days: 7

# 实时监控
cat:
  enabled: true
  home: /tmp
  servers: localhost
  tcp-port: 2280
  http-port: 8080
